version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=userName
      - RABBITMQ_DEFAULT_PASS=userSecretPassword
